In [6]:
import numpy as np

a=np.array([1,5,4])
a1=np.array([[1,3,4],[5,6,7]])
print(a)
print(a1)

print(a1[1][2]) #reading 2nd index 3rd value
#      c0 c1 c2 c3
#R0  3   4    5   6
#R1   2   4   6   7
#R2   5   6   7   7
#R3   6   3  4    6

print(np.arange(10)) #its like a range
print(a.ndim) #dimension
print(a1.ndim)
print(a1.shape) #row column
print(a.shape)
len(a1)

[1 5 4]
[[1 3 4]
 [5 6 7]]
7
[0 1 2 3 4 5 6 7 8 9]
1
2
(2, 3)
(3,)


2

In [10]:
#python list
#time taken to run the loop

l=range(1000)
%timeit a**2

781 ns ± 60.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [9]:
l=np.arange(1000)
%timeit l**2

2.03 µs ± 123 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [12]:
#creating array

a=np.array([[9,6,7],[5,6,7],[1,2,4]])
print(a.ndim)
print(a)
print(type(a))
a[1][2]

2
[[9 6 7]
 [5 6 7]
 [1 2 4]]
<class 'numpy.ndarray'>


7

In [13]:
#print dimension

print(a.ndim)

2


In [14]:
#shape
print(a.shape[1])

3


In [15]:
print(len(a))

3


In [17]:
a=np.array([[9,6,7],[5,6,7],[1,2,]])
print(a.ndim)
print(a)
print(type(a))
print(a[1][1])
a[1][1]=6
print(a)

1
[list([9, 6, 7]) list([5, 6, 7]) list([1, 2])]
<class 'numpy.ndarray'>
6
[list([9, 6, 7]) list([5, 6, 7]) list([1, 2])]


<ipython-input-17-07ee0681ea2e>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  a=np.array([[9,6,7],[5,6,7],[1,2,]])


In [23]:
#multidimensional 

ls=np.array([[[9,6,7],[5,6,7]],[[1,2,4],[3,4,7]]])
print(ls)
ls[0][1][2] #1st metrics, 2nd row, 3rd column
print(ls.shape)
print(ls.ndim)

[[[9 6 7]
  [5 6 7]]

 [[1 2 4]
  [3 4 7]]]
(2, 2, 3)
3


In [25]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
#start, end(exclusive),step
a=np.arange(10,1,3)
a

array([], dtype=int32)

In [33]:
a=np.linspace(1,2,4) #start, endn number of division (4)
#will divide value between 1 to 2in 4 parts
a

array([1.        , 1.33333333, 1.66666667, 2.        ])

In [28]:
a=np.zeros((3,4)) #matrix of 3X4
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
a=np.ones((3,4)) #matrix of 3X4
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
a=np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
a=np.eye(2,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [36]:
a=np.diag([1,2,3,4,5])
a.shape
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [37]:
np.diag(a)

array([1, 2, 3, 4, 5])

In [38]:
np.random.rand(4)

array([0.14400189, 0.74258485, 0.83405753, 0.33824837])

In [39]:
#random=rand
#n is normal distribution
np.random.randn(4)

array([ 1.26538085,  0.35063513, -0.20805455,  0.32328054])

In [44]:
ab=np.arange(10)
ab.dtype
#print(type(ab))
#ab

dtype('int32')

In [42]:
a=np.arange(10,dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])