In [1]:
from  scipy import constants

print(constants.liter)
print(constants.hour)
print(constants.pi)
print(dir(constants))

0.001
3600.0
3.141592653589793
['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_obsolete_constants', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'golden_ratio', 'gra

In [2]:
import scipy

print(scipy.__version__)

1.5.2


In [4]:
import numpy as np
from scipy.sparse import csr_matrix

arr=np.array([0,0,0,0,0,1,1,0,2])

print(csr_matrix(arr))

  (0, 5)	1
  (0, 6)	1
  (0, 8)	2


In [5]:
import numpy as np
from scipy.sparse import csr_matrix

arr=np.array([[0,0,0],[0,0,1],[1,0,2]])

print(csr_matrix(arr).data)

[1 1 2]


In [6]:
import numpy as np
from scipy.sparse import csr_matrix

arr=np.array([[0,0,0],[0,0,1],[1,0,2]])

print(csr_matrix(arr).count_nonzero())

3


In [7]:
import numpy as np
from scipy.sparse import csr_matrix

arr=np.array([[0,0,0],[0,0,1],[1,0,2]])

mat=csr_matrix(arr)
mat.eliminate_zeros()
print(mat)
print(arr)

print(csr_matrix(arr))

  (1, 2)	1
  (2, 0)	1
  (2, 2)	2
[[0 0 0]
 [0 0 1]
 [1 0 2]]
  (1, 2)	1
  (2, 0)	1
  (2, 2)	2


In [8]:
import numpy as np
from scipy.sparse import csr_matrix

arr=np.array([[0,0,0],[0,0,1],[1,0,2]])

mat=csr_matrix(arr)
mat.sum_duplicates()
print(mat)

  (1, 2)	1
  (2, 0)	1
  (2, 2)	2


In [10]:
import numpy as np
from scipy.sparse import csr_matrix

arr=np.array([[0,0,0],[0,0,1],[1,0,2]])

newarr=csr_matrix(arr).tocsc()

print(newarr)

  (2, 0)	1
  (1, 2)	1
  (2, 2)	2
